import React from 'react';
import { 
  LayoutDashboard, 
  KanbanSquare, 
  CalendarDays, 
  Users, 
  Settings, 
  LogOut, 
  Hexagon,
  MessageSquare,
  Send,
  Paperclip,
  Bot,
  X,
  Menu,
  Bell,
  Search,
  Plus,
  Filter,
  MoreVertical,
  ChevronLeft,
  ChevronRight,
  Shield,
  Mail,
  Phone,
  Globe,
  Building2,
  Clock,
  Sparkles,
  Upload
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Board: KanbanSquare,
  Calendar: CalendarDays,
  Team: Users,
  Settings: Settings,
  Logout: LogOut,
  Logo: Hexagon,
  Chat: MessageSquare,
  Send: Send,
  Attach: Paperclip,
  Bot: Bot,
  Close: X,
  Menu: Menu,
  Bell: Bell,
  Search: Search,
  Plus: Plus,
  Filter: Filter,
  More: MoreVertical,
  Left: ChevronLeft,
  Right: ChevronRight,
  Role: Shield,
  Email: Mail,
  Phone: Phone,
  Web: Globe,
  Company: Building2,
  Time: Clock,
  AI: Sparkles,
  Upload: Upload
};

export default Icons;